# Generated by Django 5.1.2 on 2024-12-11 13:21

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='50 caractères max', max_length=50, verbose_name='Titre')),
                ('description', models.TextField(help_text='200 caractères max', max_length=200, verbose_name='Description')),
                ('slug', models.SlugField(blank=True)),
                ('price', models.IntegerField(verbose_name="Prix d'achat")),
                ('category', models.CharField(choices=[('ch', 'Chaussures'), ('pa', 'Pantalons'), ('ha', 'Hauts')], max_length=20, verbose_name='Catégorie')),
                ('pics_1', models.ImageField(upload_to=marketplace.models.user_directory_path, verbose_name='Photo 1')),
                ('pics_2', models.ImageField(blank=True, null=True, upload_to=marketplace.models.user_directory_path, verbose_name='Photo 2')),
                ('pics_3', models.ImageField(blank=True, null=True, upload_to=marketplace.models.user_directory_path, verbose_name='Photo 3')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('activate', models.BooleanField(default=False, verbose_name='Activé')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
            ],
            options={
                'verbose_name': 'Vêtement',
            },
        ),
    ]
