# Generated by Django 5.1.2 on 2024-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_options_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Activé'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ch', 'Chaussures'), ('pa', 'Pantalons'), ('ha', 'Hauts'), ('my', 'Mythique')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
