# Generated by Django 5.1.2 on 2024-12-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_activate_alter_product_user'),
        ('shop', '0008_remove_vitrine_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vitrine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.vitrine'),
        ),
    ]
