# Generated by Django 5.1.2 on 2024-12-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_product_category'),
        ('shop', '0008_remove_vitrine_proprietaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True, help_text='Activée ou Désactivée', verbose_name='Statut')),
                ('domaine', models.CharField(help_text='Domaine de la Marketplace', max_length=100, verbose_name='Domaine')),
                ('vitrine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='shop.vitrine', verbose_name='Vitrine')),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.marketplace'),
        ),
    ]
