# Generated by Django 5.1.2 on 2024-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrine',
            name='horaires',
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='description_boutique',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='description_proprietaire',
            field=models.CharField(max_length=255),
        ),
    ]
