# Generated by Django 5.1.2 on 2024-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_vitrine_horaires_alter_vitrine_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vitrine',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.tag'),
        ),
    ]
