# Generated by Django 5.1.2 on 2024-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_tag_vitrine_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrine',
            name='description_boutique',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='description_proprietaire',
            field=models.TextField(),
        ),
    ]
