# Generated by Django 5.1.2 on 2024-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_vitrine_description_boutique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='slug_vitrine',
            field=models.SlugField(blank=True, max_length=255, unique= True),
        ),
    ]
