# Generated by Django 5.1.2 on 2024-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_vitrine_proprietaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrine',
            name='proprietaire',
        ),
    ]
