# Generated by Django 5.1.2 on 2024-11-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
