# Generated by Django 5.1.2 on 2024-11-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0003_delete_profile'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
