# Generated by Django 5.1.2 on 2024-11-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0009_profile_role_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
