# Generated by Django 5.1.2 on 2024-11-25 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0013_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vitrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=255)),
                ('description_boutique', models.TextField()),
                ('nom_proprietaire', models.CharField(max_length=255)),
                ('description_proprietaire', models.TextField()),
                ('reseau_social_1', models.URLField(blank=True, null=True)),
                ('reseau_social_2', models.URLField(blank=True, null=True)),
                ('horaires', models.JSONField()),
                ('adresse', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitrine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
