# Generated by Django 5.1.2 on 2024-11-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0014_alter_customuser_date_of_birth_vitrine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrine',
            name='reseau_social_1',
        ),
        migrations.RemoveField(
            model_name='vitrine',
            name='reseau_social_2',
        ),
    ]
