# Generated by Django 5.1.2 on 2024-11-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_utilisateur'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='CustomUser',
        ),
    ]
