# Generated by Django 5.1.2 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('gestionnaire', 'Gestionnaire')], default='client', max_length=15),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
